-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 10:38:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema photography_rental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photography_rental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photography_rental` DEFAULT CHARACTER SET utf8 ;
USE `photography_rental` ;

-- -----------------------------------------------------
-- Table `photography_rental`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `mailing_address` VARCHAR(255) NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`equipment_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`equipment_model` (
  `model_id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(50) NOT NULL,
  `model_name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(50) NULL,
  `description` VARCHAR(255) NULL,
  `rental_rate` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`equipment_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`equipment_unit` (
  `unit_id` INT NOT NULL AUTO_INCREMENT,
  `serial_number` VARCHAR(50) NOT NULL,
  `unit_condition` VARCHAR(50) NULL,
  `availability_status` VARCHAR(20) NOT NULL DEFAULT 'Available',
  `model_id` INT NOT NULL,
  PRIMARY KEY (`unit_id`),
  UNIQUE INDEX `serial_number_UNIQUE` (`serial_number` ASC) VISIBLE,
  INDEX `fk_equipment_unit_equipment_model_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_unit_equipment_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `photography_rental`.`equipment_model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`rental` (
  `rental_number` INT NOT NULL AUTO_INCREMENT,
  `checkout_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `customer_id` INT NOT NULL,
  `checkout_employee_id` INT NOT NULL,
  PRIMARY KEY (`rental_number`),
  INDEX `fk_rental_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_rental_employee1_idx` (`checkout_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_rental_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `photography_rental`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_employee1`
    FOREIGN KEY (`checkout_employee_id`)
    REFERENCES `photography_rental`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`rental_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`rental_item` (
  `rental_number` INT NOT NULL,
  `line_number` INT NOT NULL,
  `condition_at_checkout` VARCHAR(50) NULL,
  `condition_at_return` VARCHAR(50) NULL,
  `return_date` DATE NULL,
  `unit_id` INT NOT NULL,
  `checkin_employee_id` INT NULL,
  PRIMARY KEY (`rental_number`, `line_number`),
  INDEX `fk_rental_item_employee1_idx` (`checkin_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_rental_item_rental1`
    FOREIGN KEY (`rental_number`)
    REFERENCES `photography_rental`.`rental` (`rental_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_item_equipment_unit2`
    FOREIGN KEY (`unit_id`)
    REFERENCES `photography_rental`.`equipment_unit` (`unit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_item_employee1`
    FOREIGN KEY (`checkin_employee_id`)
    REFERENCES `photography_rental`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_item_employee2`
    FOREIGN KEY (`checkin_employee_id`)
    REFERENCES `photography_rental`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`payment` (
  `receipt_number` INT NOT NULL AUTO_INCREMENT,
  `payment_date` DATE NOT NULL,
  `payment_type` VARCHAR(20) NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `rental_number` INT NOT NULL,
  PRIMARY KEY (`receipt_number`),
  INDEX `fk_payment_rental1_idx` (`rental_number` ASC) VISIBLE,
  CONSTRAINT `fk_payment_rental1`
    FOREIGN KEY (`rental_number`)
    REFERENCES `photography_rental`.`rental` (`rental_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`repair_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`repair_order` (
  `repair_order_id` INT NOT NULL AUTO_INCREMENT,
  `repair_date` DATE NOT NULL,
  PRIMARY KEY (`repair_order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photography_rental`.`repair_order_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photography_rental`.`repair_order_unit` (
  `unit_id` INT NOT NULL,
  `cost` DECIMAL(8,2) NULL,
  `reason` VARCHAR(255) NOT NULL,
  `repair_order_id` INT NOT NULL,
  PRIMARY KEY (`unit_id`, `repair_order_id`),
  INDEX `fk_repair_order_unit_repair_order1_idx` (`repair_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_repair_order_unit_repair_order1`
    FOREIGN KEY (`repair_order_id`)
    REFERENCES `photography_rental`.`repair_order` (`repair_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_order_unit_equipment_unit1`
    FOREIGN KEY (`unit_id`)
    REFERENCES `photography_rental`.`equipment_unit` (`unit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
